// buildscript.go
//
// Generates a PowerShell build.ps1 in the generated admin panel application as
// a Windows-native equivalent of the Makefile. Windows has no make (nor the
// POSIX sh/tar/rm utilities the Makefile targets rely on), so the build, run,
// package and clean workflows are mirrored here in PowerShell. The script is
// emitted alongside the Makefile (which stays the primary build entrypoint on
// Unix); both implement the same targets: build (templ + go build), templ, tidy,
// run, package and clean. No npm/node, no sqlc and no Tailwind are required.
package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// generateBuildScript writes build.ps1 into the output directory, mirroring the
// Makefile targets so the generated app builds on Windows without make/WSL.
// The binary is named after the output directory base name (matching the
// module name written to go.mod); on Windows the built artifact is
// <binary>.exe. The package target uses tar.exe (bundled with Windows 10 1803+
// and Windows 11) so no external tools are needed.
// Returns an error on write failure.
func (g *Generator) generateBuildScript() error {
	binary := filepath.Base(g.OutDir)
	script := fmt.Sprintf(
		"# build.ps1 generated by YAGA - mirrored Makefile targets for Windows.\n"+
			"# Usage: powershell -ExecutionPolicy Bypass -File .\\build.ps1 <target>\n"+
			"# Targets: build (default), templ, tidy, run, package, clean - all\n"+
			"# equivalent to the same-named make targets. No make, npm, sqlc or Tailwind\n"+
			"# required: the stylesheet is pre-built and vendored at generation time,\n"+
			"# Chart.js is embedded in the binary, and the schema comes from the\n"+
			"# config's captured schema: block.\n"+
			"\n"+
			"param(\n"+
			"    [string]$Target = \"build\",\n"+
			"    [string]$Binary = \"%s\",\n"+
			"    [string]$Log = \"full\",\n"+
			"    [int]$Port = 8080,\n"+
			"    [string]$PackageName = \"\"\n"+
			")\n"+
			"\n"+
			"$ErrorActionPreference = \"Stop\"\n"+
			"\n"+
			"function Invoke-Step {\n"+
			"    param([string]$Command)\n"+
			"    Write-Host \"==> $Command\"\n"+
			"    Invoke-Expression $Command\n"+
			"    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }\n"+
			"}\n"+
			"\n"+
			"switch ($Target) {\n"+
			"    \"tidy\" {\n"+
			"        Invoke-Step \"go mod tidy\"\n"+
			"    }\n"+
			"    \"templ\" {\n"+
			"        Invoke-Step \"go mod tidy\"\n"+
			"        Invoke-Step \"go tool templ generate\"\n"+
			"    }\n"+
			"    \"build\" {\n"+
			"        Invoke-Step \"go mod tidy\"\n"+
			"        Invoke-Step \"go tool templ generate\"\n"+
			"        Invoke-Step \"go build -o $Binary.exe .\"\n"+
			"    }\n"+
			"    \"run\" {\n"+
			"        Invoke-Step \"go mod tidy\"\n"+
			"        Invoke-Step \"go tool templ generate\"\n"+
			"        Invoke-Step \"go build -o $Binary.exe .\"\n"+
			"        Invoke-Step \"& .\\\\$Binary.exe --port $Port --log $Log\"\n"+
			"    }\n"+
			"    \"package\" {\n"+
			"        Invoke-Step \"go mod tidy\"\n"+
			"        Invoke-Step \"go tool templ generate\"\n"+
			"        Invoke-Step \"go build -o $Binary.exe .\"\n"+
			"        if (-not $PackageName) { $PackageName = \"$Binary-$((Get-Date -Format yyyyMMdd))\" }\n"+
			"        Remove-Item -Recurse -Force $PackageName -ErrorAction SilentlyContinue\n"+
			"        New-Item -ItemType Directory -Force -Path $PackageName | Out-Null\n"+
			"        Copy-Item $Binary.exe, static -Destination $PackageName -Recurse\n"+
			"        if (Test-Path .ENV) { Copy-Item .ENV -Destination $PackageName }\n"+
			"        foreach ($d in @(\"sql\", \"data\")) {\n"+
			"            if (Test-Path $d) { Copy-Item $d -Destination $PackageName -Recurse }\n"+
			"        }\n"+
			"        Invoke-Step \"tar.exe -czf $PackageName.tar.gz $PackageName\"\n"+
			"        Remove-Item -Recurse -Force $PackageName\n"+
			"    }\n"+
			"    \"clean\" {\n"+
			"        Remove-Item -Force \"$Binary.exe\", \"$PackageName.tar.gz\" -ErrorAction SilentlyContinue\n"+
			"    }\n"+
			"    default {\n"+
			"        Write-Host \"build.ps1: unknown target '$Target'.\"\n"+
			"        Write-Host \"Usage: powershell -ExecutionPolicy Bypass -File .\\build.ps1 [build|templ|tidy|run|package|clean]\"\n"+
			"        exit 1\n"+
			"    }\n"+
			"}\n",
		binary)
	return os.WriteFile(filepath.Join(g.OutDir, "build.ps1"), []byte(script), 0644)
}